export const queryKeys = {
  contentsWave: 'contentsWave',
  contentsWeather: 'contentsWeather',
  youtubeContents: 'youtubeContents',
  haenyeoPlacesLocations: 'haenyeoPlacesLocations',
  haenyeoPlaceDetail: 'haenyeoPlaceDetail',
  seafoodsCollectionsStatus: 'seafoodsCollectionsStatus',
  seafoodsCollections: 'seafoodsCollections',
  seafoods: 'seafoods',
  journalCreatePlace: 'journalCreatePlace',
  analyzedSeafoodImage: 'analyzedSeafoodImage',
  journals: 'journals',
  journalDetail: 'journalDetail',
  journalDetailCollections: 'journalDetailCollections',
  myPage: 'myPage',
  myPageBadge: 'myPageBadge',
};
